FROM python:3-slim

# Create the necessary directory structure
RUN mkdir -p /app/

# Install Git
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy application files
COPY main.py /app/main.py

# Set the command to run the application
CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080","--log-level", "info"]